# 本地配置文件
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aozhou_code?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12345678
    hikari:
      maximum-pool-size: 10  # 最大连接池大小
      minimum-idle: 2  # 最小空闲连接数
      idle-timeout: 60000  # 空闲连接超时时间（单位：毫秒）
      max-lifetime: 1800000  # 连接最大生命周期（单位：毫秒）
      connection-timeout: 30000  # 连接超时（单位：毫秒）
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 121.40.137.170
    port: 6379
    timeout: 5000
    password: redis123
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # 生产环境关闭日志
    log-impl: ''

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.aozhou.code.controller
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: sa-token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
